### ISSUE TITLE
Anyone need office hours today?

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Spring-Forum#101]
I'll be on campus from approximately 4-6pm today. If anyone would like to go over their final assignment please respond here or email. I'd be happy to go through your final with you. :)

**Comment by Jerry-J-Yu** [comment]
Are you in the Crerar lab?

**Comment by bobby-digital-23** [comment]
I'm in Reg but will walk over to Crerar.  Be there in 10-15min. Are you already there?

**Comment by Jerry-J-Yu** [comment]
I'm not, but I can get there in 30 min

**Comment by bobby-digital-23** [comment]
Ok, I'll see you there around 4:45pm. Let's meet in CSIL 1 or 2 - whichever is free.

Anyone else?

**Comment by bobby-digital-23** [comment]
Sorry, I have to leave now. For anyone with further questions, please post them to the forum. Good luck on all of your finals! :)
