### ISSUE TITLE
Juggle 24

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Spring-Forum#102]
Juggle 24 is now in the App Store!  Sat waiting in review for 10 days... lol

Here is a link if you'd like to play https://appsto.re/us/RM9q7.i

**Comment by tabinks** [comment]
Congrats！

**Comment by xiaoyifan** [comment]
Already download it ! Congrats!

**Comment by xiaoyifan** [comment]
Already downloaded it ! Congrats!

**Comment by jhergott** [comment]
Thanks!
