### ISSUE TITLE
Class Tomorrow

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#103]
Just a reminder, tomorrow's app presentations are casual, no slides needed.  Just show your work off and answer some questions from your fellow developers.

If you would like me to preload your app on iPad let me know. If not, you can plug in your own device.

Don't forget that WWDC keynote is tomorrow!  There will be (hopefully) much to discuss.

**Comment by tabinks** [comment]
Also, I am bringing some snacks tonight :)

**Comment by tabinks** [comment]
And the WWDC live stream is starting...

**Comment by JRam13** [comment]
Watching it live for the first time. Want to go in the pool though, really nice day down here

:)

**Comment by JRam13** [comment]
Thats not how ransom works... but ok.

**Comment by JRam13** [comment]
Ransom*

**Comment by tabinks** [comment]
If there is anyone who needs free stuff, its professional athletes...

**Comment by xiaoyifan** [comment]
we can also go through some cool things tonight ~
