### ISSUE TITLE
Fall of the Designer

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#107]
Required post-finals reading!

A great 5-part series on how design is evolving and how it affects software, designers, and developers. The writing could use a bit more clarity, but overall it’s quite insightful and thought-provoking.

http://www.elischiff.com/blog/2015/4/7/fall-of-the-designer-part-i-fashionable-nonsense

**Comment by alextsu** [comment]
I like the article a lot. I personally think that good design should be easy.Prior to iOS7, the difficulty of making things appear visually appealing is a fault of the design paradigm and not the skill of the designer.

**Comment by tabinks** [comment]
Seriously?

**Comment by tabinks** [comment]
7 years later.

**Comment by JRam13** [comment]
LOL this is hilarious
