### ISSUE TITLE
Reminder: Office hours TODAY (Friday) at Crerar - 4:00pm

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Spring-Forum#14]
Come learn some Swift with me. 

![](http://qph.is.quoracdn.net/main-qimg-55b26d0b27d2e0e273dc5f28d60e1bba?convert_to_webp=true)

**Comment by tabinks** [comment]
Remember that attending office hours is `Optional` :)

**Comment by JRam13** [comment]
![](http://cdn.meme.am/instances/60915255.jpg)

**Comment by bobby-digital-23** [comment]
In case you need some theme music for office hours ;)

https://m.youtube.com/watch?feature=youtu.be&v=vEg4SEch27w

**Comment by JRam13** [comment]
I'm here now, so stop by if you need help. I'm towards the back. I think from 4:30-6 we have room CSIL-2
