### ISSUE TITLE
Sound Effect

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#16]
I have a question about the sound effect. For each page, it has its sound effect. The user can tap the play sound button. The sound last several seconds. What if the user swipe to the next page at this time? Is the sound paused? Do I put this pause in the viewDidDisappear?

**Comment by JRam13** [comment]
There are two options, either stop all user interaction while there is sound, or cancel your sounds when the page is flipping. 

Stopping user interaction is always a bad idea in my opinion, it really can hinder user experience. Even if the sound is a few seconds long.
