### ISSUE TITLE
HeaderDoc comments

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#18]
I see that we're required to comment our code using the HeaderDoc syntax. I don't see HeaderDoc support for Swift yet. Should we just use the Obj-C commenting syntax for now—or something else?

**Comment by tabinks** [comment]
It works in a slightly different format, but that is true it not officially supported yet.
Check out http://nshipster.com/swift-documentation/ for some examples.

Here is the basics....
    /**
        Initializes a new bicycle with the provided parts and specifications.

```
    :param: style The style of the bicycle
    :param: gearing The gearing of the bicycle
    :param: handlebar The handlebar of the bicycle
    :param: centimeters The frame size of the bicycle, in centimeters

    :returns: A beautiful, brand-new, custom built just for you.
```

*/

**Comment by drefiuza** [comment]
Awesome, thanks!
