### ISSUE TITLE
WWDC 2015 is coming !!!!

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#22]
This is a big iOS news day. WWDC 2015 announced for June 8-12 to unveil “the future of iOS and OS X”

The ticket to WWDC 2015 is very expensive ($1599.0). However, as students, we have chances to win WWDC scholarships! Developers selected for a scholarship will receive a WWDC 2015 ticket free of charge.

THE DEADLINE IS April 26 at 5:00 p.m. PDT

https://developer.apple.com/wwdc/scholarships/

**Comment by alextsu** [comment]
Time to wow Tim Cook with our 6 page storybook apps

**Comment by tabinks** [comment]
If anyone is thinking of submitting an app, please let me know.

**Comment by drefiuza** [comment]
If I don't get a ticket through the general lottery, I plan to submit an app.

**Comment by bobby-digital-23** [comment]
Thanks for providing that link Yi! 

I still remember when you rocked your WWDC '14 jacket in the last class. Knew we had a troublemaker. 😉 

What did you think of the actual event? For someone who is already a paid Apple developer (who can watch most of the events from the comfort of home), are the networking opportunities worth the extra $1600 + transportation/accommodation costs?

**Comment by xiaoyifan** [comment]
It's damn cool, wanna be a guy in it

**Comment by tabinks** [comment]
I've been before...back in the day before it would sell out in minutes.  It's was a great event for learning about new technologies (since there were no release videos), now I think it's a really great event for networking (or job hunting).

The one great feature they have (that you don't get form the videos), is technology "labs", where you can go sit with Apple engineers and pick their brains.  You can actually bring your code and they'll look at your problems.  This is pretty invaluable and the only place you can get this kind of attention.

**Comment by yiqin** [comment]
@bobby-digital-23 From my experience, WWDC also provides other things. WWDC have two different session- Lab and Tutorial. Tutorial have videos online, but Lab doesn't. Many programmers go to WWDC just to talk with Apple Engineers at Lab. Some of they don't go to the tutorials which are accessed online. You also have chances to schedule a 30 mins session with the UI & UX team, which is the most popular lab session at WWDC. They will give feedback on app design and user experience.

**Comment by bobby-digital-23** [comment]
Wow, that is excellent info. Thank you both!

Dang, now I'm tempted to register! However, I am worried that if I luck into a ticket and then can't attend for any reason, I'd lose a large chunk of money. It says tickets are non-transferable and no refunds. The only exception with transfers seems to be amongst team members but even that seems to be at Apple's discretion. Decisions, decisions... 😊

https://developer.apple.com/wwdc/more/

**Comment by bobby-digital-23** [comment]
For those of you who are applying for the WWDC scholarship and for those of you who have any interest in Swift, Erica Sadun (author of several excellent iOS dev books) made this interesting observation. 😊

http://ericasadun.com/2015/04/14/swift-in-case-you-didnt-think-that-swift-was-the-future/

**Comment by JRam13** [comment]
I wonder if I can apply to this...

**Comment by alextsu** [comment]
On a related note,  if you need food/tourism recommendations from a SF Bay Area native let me know. My rates are much more reasonable than $1599 ;)
