### ISSUE TITLE
iTunes Search API Limit is 200

### ISSUE THREAD

**Issue by emondai** [uchicago-mobi/2015-Spring-Forum#23]
The iTunes Search API doesn't allow more than 200 results and I can't find anything on a search offset or pagination. Any ideas?

**Comment by tabinks** [comment]
I was going from memory and though the limit was 250.  **For the assignment, you can use 200.**  I will update the assignment description.

However, if you want to use more, just vary your search a bit: 
- search=flappy
- search="flappy bird"
- search="bird games"
- etc.

**Comment by bobby-digital-23** [comment]
https://www.apple.com/itunes/affiliates/resources/documentation/itunes-store-web-service-search-api.html

I like the example they use for the "*censoredName" JSON result key. 😊

**Comment by emondai** [comment]
Okay, thanks. I'll set it at 200 then.
