### ISSUE TITLE
Array Core Data

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Spring-Forum#25]
Is there a best practice for storing arrays in core data?

**Comment by tabinks** [comment]
You could use a `NSData` blob which is capable of storing anything that conforms to `NSCoding`.  

If you are talking about the search terms, I would think about just putting them in a string attribute in your Application entity.  `NSPredicate` has built in search term `CONTAINS[cd]` which will do a substring search.  The `[cd]` makes it case-insensitive.  

```
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"searchterms CONTAINS[cd] %@",
                             searchBar.text];
```

You could also create a **SearchTerm** Entity and create a one-to-many relationship back to the **Application** Entity.  The you would query against **SearchTerms** and map them back to their **Application** entities.

My intuition thinks that the second way would have better performance in our case, but it would be an interesting exercise to see, in practice, what would perform better.  The first would would be more straightforward to implement.

**Comment by xctom** [comment]
This one would work. I set the type to "Transformable"

```
var ipadScreenshotUrls:[String] = [String]()
item.setValue(ipadScreenshotUrls, forKey: "ipadScreenshotUrls")
```

**Comment by jhergott** [comment]
thanks for these notes
