### ISSUE TITLE
AFNetworking in Assignment 2

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#26]
Could we use AFNetworking to handle the HTTP request in Assignment 2?

**Comment by tabinks** [comment]
No...not because it's bad, but because you shouldn't really need it.  Just use `NSURLSession` for your CoreData builder application.  Performance isn't an issue since you're just running this for yourself.

CloudKit, CoreData w/iCloud, Parse all have built in networking capabilities.
