### ISSUE TITLE
Office hours - Friday @ TBD Afternoon Time - Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Spring-Forum#3]
Hi everybody,

Office hours tomorrow at Crerar. Just waiting to see if we get a lab all to ourselves (fancy 😊). 

I'll post the exact time and location as soon as I know. 

Looking forward to a great quarter!

Best,
Bobby

**Comment by tabinks** [comment]
@bobby-digital-23 We have CSIL-1 reserved from 3-5pm on Fridays.
