### ISSUE TITLE
Office hours - Friday @ 3pm - Crerar CSIL 1

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Spring-Forum#4]
Our professor confirmed that we have CSIL 1 on Fridays from 3-5pm!

CSIL 1 is the first Mac lab to the left in the Crerar library. Please look at the following site if you're unsure of the location:
http://csil.cs.uchicago.edu

Please let me know if you might attend. See you all tomorrow and happy spring quarter! 😊

**Comment by Jerry-J-Yu** [comment]
I'll be there.
