### ISSUE TITLE
Copying sqlite file to new project

### ISSUE THREAD

**Issue by emondai** [uchicago-mobi/2015-Spring-Forum#43]
How can we manually copy over the data file we created in our first application? I copied the sqlite file to the new project's directory and changed the url of the persistentStoreCoordinator but when my code runs the coredata file is empty. Any ideas?

**Comment by tabinks** [comment]
Make sure you are trying to read it from the main bundle's directory not from Documents directory.

**Comment by emondai** [comment]
I got it to read the file correctly but it is empty for some reason

**Comment by emondai** [comment]
When I added rows only the .sqlite-shm and sqlite-wal files were modified. I added those to my second project too but nothing changed.

**Comment by tabinks** [comment]
Try opening the .sqlite file from the terminal to verify that there is data written there.  

```
>sqlite3 file_name
```

It's not easy to read, but you can usually tell if it is empty or not.

**Comment by emondai** [comment]
I got it working. I made sure to stop running the application and then to grab the correct sqlite file. I may have been using the sqlite file for a different size iPhone in the simulator.
