### ISSUE TITLE
SKStoreProductViewController Parameters

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Spring-Forum#46]
What can we use from the iTunes api as a parameter for the SKStoreProductViewController?  I tried "trackId" and "artistId" and didn't get either to work.  

Note: I am getting the SKStoreProductViewController presented, but it is blank with just a cancel button in the nav bar.

**Comment by Jerry-J-Yu** [comment]
Have you tried "trackViewUrl"? or "http://itunes.com/apps/{trackName}" where {trackName} is the value from the key "trackName"?

i haven't gotten that far yet so no guarantees that those will work.

**Comment by jhergott** [comment]
Thanks for the note Jerry.  I tried the ID from trackViewUrl for SKStoreProductParameterITunesItemIdentifier, but didn't get that to work.  Any chance this doesn't work in the simulator but would work on a device?

**Comment by Jerry-J-Yu** [comment]
That might be the reason. According to [this post](http://stackoverflow.com/questions/24709586/method-does-not-reach-completion-block) they could not get it to work on the simulator because it doesn't have the iTunes Store on it.

**Comment by jhergott** [comment]
Ah ok. Thanks for that.

edit: got it working now. thanks!
