### ISSUE TITLE
Comments for Assignment 1 (Book)

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Spring-Forum#47]
Overall I was very impressed. Great job all around. From what I saw, a lot of people followed standard practices throughout.

There are two suggestions I want to make however.
1. I already posted this last quarter, and it's worth taking another look. https://github.com/uchicago-mobi/2015-Winter-Forum/issues/229
2. Organizing your onViewMethods (viewDidLoad/viewWillAppear/etc...). 

I understand that there are probably a lot of things going on when your view first loads, so it's understandable it might get a bit lengthy with all the setup code. However, if you feel like it's going on forever, break it up, refactor, or encapsulate some of your onView code. 

Example:

ViewController.m

``` objC
- (void)viewDidLoad
 {
     _puzzleSpeed = 1;
    _puzzlePieces = [[NSMutableArray alloc] init];
    _randomizedPuzzlePieces = [[NSMutableArray alloc] init];
    _alphabet = [[NSArray alloc] initWithObjects:@"A", @"B", @"C", @"D", @"E", @"F", @"G", @"H", @"I", @"J", @"K", @"L", @"M", @"N", @"O", @"P", @"Q", @"R", @"S", @"T", @"U", @"V", @"W", @"X", @"Y", @"Z", nil];
    _wordProgress = [[NSMutableArray alloc] init];
    _lettersTapped = [[NSMutableArray alloc] init];
    _hints = [[NSMutableArray alloc] init];
    .
    .
    .
    this
    goes
    on
    forever
    .
    .
    .
}
```

BECOMES

ViewController.m

``` objC
#pragma mark - OnView Methods
- (void)viewDidLoad
 {
    [super viewDidLoad];

    //initialize variables
    [self initVars];

    //setup view
    [self initViews];

    //initialize/setup puzzle
    [self setupPuzzle];

    //display puzzle
    [self displayPuzzle];

    //setup timers
    [self setupTimers];
}

#pragma mark - UI
-(void)initViews{...}
-(void)displayPuzzle{...}

#pragma mark - Timers
-(void)setupTimers{...}

#pragma mark - Helpers
-(void)initVars{...}
-(void)setupPuzzle{...}
```

Much more readable, don't you think?

**Comment by xctom** [comment]
Hi, Jonny. My HW1 is not graded yet. Would you mind check it for me?

**Comment by bobby-digital-23** [comment]
@xctom - We are still in the process of grading assignment 1. You should have it by class on Monday. Have a good weekend. :)

**Comment by xctom** [comment]
@bobby-digital-23 Thanks!
