### ISSUE TITLE
deleting data on Parse

### ISSUE THREAD

**Issue by xiaoyifan** [uchicago-mobi/2015-Spring-Forum#48]
I'm trying to use both of Core data and Parse for data operation. Since I wanna fetch the data everytime when the app is launched, I wanna clean my database in viewDidLoad. the Core data did fine, but Parse would give me warning "A long-running operation is being executed on the main thread". I guess the right way would be using GCD or NSOperation to handle it in another thread, but deleting the data should be executed before new data downloading. Is there any suggestion on that?

**Comment by JRam13** [comment]
Which parse function are you calling?

**Comment by xiaoyifan** [comment]
let query = PFQuery(className: "musicStore")

```
    query.findObjectsInBackgroundWithBlock {
        (objects: [AnyObject]?, error:NSError?) -> Void in

        for object in objects as! [PFObject] {
            object.delete(nil)
        }
    }
```

just a simple query to get all the data, and delete them

**Comment by xiaoyifan** [comment]
it might spends a long time, so parse gives me warning.

**Comment by JRam13** [comment]
Yes. Use 

```
deleteInBackground()
```

**Comment by xiaoyifan** [comment]
It works! Thx! So how does Parse process the data in background? If data will be deleted in another thread, how can we assure that all the data will be deleted before downloading them again?

**Comment by JRam13** [comment]
I'm not sure what you're trying to do. I understand your question, but try to talk me through why you're deleting your data the way you are.

**Comment by xiaoyifan** [comment]
OK, I just wanna update at the beginning of launching app. So I wanna delete what I have in database and download again. So the process should be delete--> download and store new data to parse. I'm not sure how deleteInBackground could ensure that all data will be deleted before I store new things in the table.

**Comment by JRam13** [comment]
Ok. In that case, you're going to want to wrap your code in a completion block. That way, once you're finished deleting everything, send back the completion to your viewDidLoad. Then, you can go ahead with downloading the new data.

Let me know if this makes sense. I can provide an example if necessary.

**Comment by xiaoyifan** [comment]
Ok, I understand the basic scenario, but can you provide me with an example on send the completion to ViewDidLoad? I don't really get this part

**Comment by JRam13** [comment]
YourViewController.m

``` objC
- (void)viewDidLoad 
{
    [super viewDidLoad];

    //delete data
    [[ParseHelper sharedInstance] deleteDataWithCompletion:^(BOOL success) {
        if (success) {
             //download data
        }
    }];
}
```

ParseHelper.m

``` objC
-(void) deleteDataWithCompletion:(void (^)(BOOL success))completionBlock
{
    .
    .
    your query code
    .
    .

    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {

        if (error){
            completionBlock(NO);
            return;
        }

        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

            for (PFObject *object in objects) {
                [object delete];
            }

             dispatch_async(dispatch_get_main_queue(), ^{
                   completionBlock(YES);
             });
         });
    }];


}
```

Notice that I removed deleteInBackground() and replaced it with GCD. This will ensure that the delete method will be executed and completed on every iteration of the for loop before moving on.

**Comment by xiaoyifan** [comment]
Awesome！ Great sample！Thx！

**Comment by JRam13** [comment]
Even easier:

``` objC
-(void) deleteDataWithCompletion:(void (^)(BOOL success))completionBlock
{
    .
    .
    your query code
    .
    .

    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {

        if (error){
            completionBlock(NO);
            return;
        }

         [PFObject deleteAllInBackground:objects block:^(BOOL succeeded, NSError *error) {
            if(succeeded){
                completionBlock(YES);
            }
            else{
                completionBlock(NO);
            }
        }];
    }];


}
```

**Comment by JRam13** [comment]
So instead of iterating through all the objects...

``` Swift
for object in objects as! [PFObject] {
      object.delete(nil)
}
```

You can call 

``` Swift
deleteAllInBackground(objects) 
```

:)

**Comment by xiaoyifan** [comment]
cool, that's even simpler!

**Comment by JRam13** [comment]
yeah, the hard part is translating the objective c code into proper Swift syntax... good luck.

**Comment by xiaoyifan** [comment]
I miss objective-c.......
