### ISSUE TITLE
Super Awesome Tips for Share Extension from App Store

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#52]
I updated the [Session5-ShareExtension](https://github.com/uchicago-mobi/MPCS51032-2015-Spring-Playgrounds) code to specifically extract relevant information that the App Store makes available to share extensions.  Please look at it and read the notes inline.  

These are the item types available from the AppStore:

```
        "<NSItemProvider: 0x170244140> {types = (\n    \"public.image\"\n)}",
        "<NSItemProvider: 0x170244320> {types = (\n    \"public.plain-text\"\n)}",
        "<NSItemProvider: 0x170244410> {types = (\n    \"public.url\"\n)}"
```

Note that `url` is the app store url for the app, `plain-text` is the title of the app, `image` is the app icon.  The icon is returned as `UIImage` so you'll need to figure out what to do with it depending on your application.  In the example, I am saving the image as `NSData` in user defaults, which is a worst-practice (but it does work).  

I made a short screen capture to show it in actions: http://goo.gl/EsDqFy

Remember that the items that come back from Safari are not the same as the ones that come back from App Store.  To fully test it, you will need to run it on a device.

**Comment by jhergott** [comment]
Thanks for this tip.  

I'm using Parse to store my Wishlist.  However when I try to "import Parse" in my ShareViewController.swift file I get an error saying "No such module 'Parse'".  Is there a way I can connect the extension target to use all my linked binaries from my app?  Also, if that is possible, is it able to use the Parse keys in the AppDelegate?

**Comment by tabinks** [comment]
> when I try to "import Parse" in my ShareViewController.swift file I get an error saying "No such module 'Parse'".

This error usually means that the framework is not built.  Select the framework target and build it first, then try building your app.  For some reason this happens randomly (in my experience).  Also, make sure that you are linking the binary in the target.  It should show up in "Linked Frameworks and Binaries"

![screenshot 2015-04-29 15 30 27](https://cloud.githubusercontent.com/assets/93689/7400738/b60a4a00-ee84-11e4-864d-700bbe9274aa.png)

> Is there a way I can connect the extension target to use all my linked binaries from my app? Also, if that is possible, is it able to use the Parse keys in the AppDelegate?

I do not believe that is possible...but I've never tried.  You can put the parse keys in your shared framework and then access that from both apps.

**Comment by jhergott** [comment]
Thank you!  It's working now.  Didn't realize I had to link the frameworks again.

Unrelated question. If we only have access to three attachments with the App Store extension... how can we for instance get access to the trackViewUrl?  Is it ok if our detail view doesn't work ideally for wishlist apps saved from the real App Store?

**Comment by emondai** [comment]
I was wondering about that too since the URL returned by the app store's share extension is a shortened one.

**Comment by tabinks** [comment]
From the favorites, you can have a tap take you:
- Directly to the app store
- Launch the SKProductViewController
- Show you detail screen

It's up to you.

**Comment by danakatz** [comment]
When I try to open the provided URL, it launches Safari and then says it can't open the page because of an invalid URL. Is there a way to specify that it should open it in the App Store?

**Comment by tabinks** [comment]
This works to launch the App Store app directly to the URL.  Notice you have to replace `https:`  with `itms-apps://`

``` swift
UIApplication.sharedApplication().openURL(NSURL(string: "itms-apps://appsto.re/us/6iThB.i")!)
```

**Comment by danakatz** [comment]
Thanks!
