### ISSUE TITLE
Apple presenting WatchKit & ResearchKit on campus next week

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#53]
In case anyone is interested:

https://appchallenge.uchicago.edu/content/apple-presents-watchkit-and-researchkit-55-2pm

"Join the App Challenge and Apple to discuss the programming tools and opportunities available in WatchKit and the recently released ResearchKit.  Come learn more about these two new programs and bring your questions for the Apple Consulting Engineer who will be presenting this new material."

**Comment by xiaoyifan** [comment]
That's damn good! Let's go~ already registered~

**Comment by xiaoyifan** [comment]
Thx for sharing!

**Comment by bobby-digital-23** [comment]
Thanks for posting this Andre!

I went last year and it was pretty fun although crowded. I signed up again this year. See you all there! :)

**Comment by JRam13** [comment]
I'll be there.

**Comment by drefiuza** [comment]
I promise to make my ResearchKit presentation more interesting than theirs.

**Comment by bobby-digital-23** [comment]
We're holding you to that promise now Andre. ;)
