### ISSUE TITLE
Does the share extension need app groups to function properly?

### ISSUE THREAD

**Issue by Jerry-J-Yu** [uchicago-mobi/2015-Spring-Forum#59]
With Jonny's help, I was able to get the Share Extension to appear when I am in the app store. But if I post an app with the extension, it doesn't seem to save anything because when I try to print out the value contained in LocalDefaultsManager.sharedInstance.currentList(), it is an empty array.

I'm trying to enable app groups to see if that allows the extension to save the app, but it throws an error saying "No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups"

**Comment by tabinks** [comment]
If you are writing to user defaults, you will need to use app groups.
If you are writing the data to parse, you can write directly from the share extension.

I posted the provisioning profile two weeks ago to make sure everyone tested it to make sure that they could get it working. https://github.com/uchicago-mobi/2015-Spring-Forum/issues/39

**Comment by Jerry-J-Yu** [comment]
I installed the provisioning profile, and then tried setting the bundle identifier of all the targets to "mobi.uchicago.CloudDataSync." This cannot be done for the Share Extension though, because it has the bundle identifier "mobi.uchicago.Game-Store.ShareExtension", and Xcode refuses to let me remove the ".ShareExtension" part of the identifier. 

Should I create a share extension from scratch and name it "Cloud Data Sync" instead of "Share Extension"?

**Comment by Jerry-J-Yu** [comment]
Nvm, I decided to use Parse instead and now it works. 

Thanks.
