### ISSUE TITLE
Running playgrounds

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#6]
Has anyone been able to successfully run the playgrounds posted by Andrew? I have Xcode 6.3 beta 4, which opens, but then I see a blank text editor (below). I have, however, been able to run other playground files from Apple's site.

![screenshot 2015-04-05 09 54 31](https://cloud.githubusercontent.com/assets/1236521/6997227/e9be2dee-db79-11e4-8ee9-eeab18f4f131.png)

**Comment by tabinks** [comment]
I moved them to a repo.  Try downloading and running these instead:

https://github.com/uchicago-mobi/MPCS51032-2015-Spring-Playgrounds

**Comment by tabinks** [comment]
If anyone has any suggestions or additions, Please submit a pull request.  We can all work together to improve the playgrounds.

**Comment by tabinks** [comment]
Also, if you want to add an additional playground as well.

**Comment by drefiuza** [comment]
Thanks! The Guided Tour file works. The other two Session 1 files from the repo open in a blank editor; same as the original screenshot.

**Comment by tabinks** [comment]
Check out the new versions in the Github repo and let me know if they work: https://github.com/uchicago-mobi/MPCS51032-2015-Spring-Playgrounds
