### ISSUE TITLE
Linking to App Store from Favorites List

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#60]
This is duplicate of answer in #52.

This works to launch the App Store app directly to the URL.  Notice you have to replace `https:`  with `itms-apps://`in the `URL` that comes from the sharing extension.

``` swift
UIApplication.sharedApplication().openURL(NSURL(string: "itms-apps://appsto.re/us/6iThB.i")!)
```

**Comment by alextsu** [comment]
Not sure if anyone else encounter this, but I tried the itms-apps:// URL and, while the URL led to the app store, it only opened up the home page of the app store. It did not open the particular App page that I was looking for. 

I tried the regular https:// URL and my app opened up safari, and safari, in turn, opened up the correct app page in the App Store.

Was this the case for anyone else as well?

**Comment by drefiuza** [comment]
I didn't append https:// or itms-apps:// and all links are working for me, as you described—safari -> app store.

**Comment by tabinks** [comment]
That's interesting.  I tried on a couple devices and I go directly to app store with a redirect from Safari.  Either way, don't worry about it.  As long you as you get to the App Store, that will be ok for the assignment.

**Comment by Jerry-J-Yu** [comment]
I sort-of encountered this. When I use "itms-apps://", on the first launch from the wish list it will go to the correct App page on the app store, but on any subsequent launches it will just go to the app store home page.
