### ISSUE TITLE
Office hours TODAY (Friday) at Crerar - 3:00pm - SpriteKit Time!

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Spring-Forum#65]
Come build your spritekit games with me.

I'll be working on my presentation for Monday as well.

**Comment by tabinks** [comment]
What if there was a game where a bird tries to dodge pipes by flapping its wings....

**Comment by drefiuza** [comment]
I recommend that you all play Flappy Stache… It’s incredibly well executed. (Not a joke).

**Comment by JRam13** [comment]
Andrew, thats pretty ridiculous. That'll never make money.
