### ISSUE TITLE
WWDC Scholarship Winner

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#66]
Please join me in congratulating Yi.  He was awarded one of the WWDC scholarships!  

He said he owes it all to CoreData :)

**Comment by JRam13** [comment]
Nice! Beers for everyone on Yi's behalf (and tab).

**Comment by drefiuza** [comment]
![](http://media2.giphy.com/media/dOJt6XZlQw8qQ/giphy.gif)

**Comment by alextsu** [comment]
![](http://www.quickmeme.com/img/e6/e6ecab80668a6c6221e727f3ec246996416ab3a12a1043c25f3500a3e27fe8a9.jpg)

**Comment by bobby-digital-23** [comment]
On behalf of Citizen Kane, Gatsby, the rest of the class (that's some great company there!), and myself:

Congratulations Yi!!!!

You and Andre have to get the rest of us who won't be attending some of those fancy WWDC '15 fleece jackets. ;)

**Comment by yiqin** [comment]
Thanks everyone!  :)

The project is open source now. The link is here [https://github.com/yiqin/WWDC-Scholarship-2015](https://github.com/yiqin/WWDC-Scholarship-2015)

**Comment by emondai** [comment]
Congrats!

**Comment by xctom** [comment]
Congratulations!
