### ISSUE TITLE
Repositories not created?

### ISSUE THREAD

**Issue by emondai** [uchicago-mobi/2015-Spring-Forum#67]
Have the repositories for our current assignment been created yet? I don't see one for this project.

**Comment by yiqin** [comment]
The link to slides of Session 4 and Session 6 are broken.

**Comment by tabinks** [comment]
I'm not sure why the slide links aren't working, its all on Google Drive.  Here is direct link to Session6:

https://drive.google.com/open?id=0B3XzcKIiWyccam9FU3J1dVlUODg&authuser=0

**Comment by jhergott** [comment]
I do not see my repo for assignment 3 either.

Unrelated question.  Is their a method that can reset an SKScene if you wanted to restart the game?  Or do you just have to implement that functionality yourself?

**Comment by tabinks** [comment]
Sorry, I thought I had created them all at the beginning of the year. They are all created now.

@jhergott Nope, there is no automated way to reset a scene.  You could just remove the scene and reload it, that could accomplish the same thing as long as you factor out your scene creation from the view controller loading (i.e. don't tie any game logic to the view controller that holds the scene).
