### ISSUE TITLE
It's still about AsyncDisplayKit

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#69]
I may fail to explain AsyncDisplayKit in a very good way. 

You may find this video very interesting - the most comprehensive talk yet delivered on AsyncDisplayKit. It includes:
- Definition of responsiveness, and discussion of its importance in modern client development
- Details on why AsyncDisplayKit is designed how it is, influenced by the architecture of iOS
- Overview of some of the powerful features that AsyncDisplayKit provides
- Examples of converting existing code to use AsyncDisplayKit, general tips on where to use it, and limitations.

https://www.youtube.com/v/ZPL4Nse76oY?vq=hd1080p50 

Presentation Slides (PDF): http://goo.gl/7SMyCy

**Comment by tabinks** [comment]
You did fine, but its always useful to have additional resources to learn from.
