### ISSUE TITLE
Amazon Web Services (AWS) Summit - Chicago

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Spring-Forum#71]
> Announcing the AWS Summit - Chicago, July 1
> Registration for the 2015 AWS Summit - Chicago is now open. This free event will educate new customers about the AWS platform and offer existing customers information on architecture best practices and new services. Register today to hear customer testimonials, learn from technical sessions led by AWS engineers, and get hands-on technical training. Space is limited so register now to secure your spot.

http://aws.amazon.com/summits/chicago/

For anyone that is interested in learning AWS, this is great opportunity. I would say one of the most useful things I learned in the Master's program (aside from iOS) is working with AWS. It is imperative nowadays that you guys be familiar with a cloud service like AWS, I really can't stress this enough.

**Comment by bobby-digital-23** [comment]
Thanks for this Jonny! I agree - it is very important to learn how to use a service like this. 

FYI - the technical boot camps held the day before the summit seem to cost $600. The summit itself is free.

I just signed up for the summit. If anyone else is planning on attending, let me know and perhaps we can arrange transportation to the event together. :)

**Comment by tabinks** [comment]
I don't understand why you need to know about webservices when there is CoreData with iCloud sync :)
