### ISSUE TITLE
7 days of free royalty free graphics at GraphicStock

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Spring-Forum#72]
In case any of you are looking for graphics for any of your apps (you might need to sign up for MacUpdate first which is also free, not sure). :)

"For 7 days only, GraphicStock is giving MacUpdate users complimentary access to over 250,000 images, icons, vectors,
textures, backgrounds and more."

https://www.graphicstock.com/freeimages/?utm_campaign=MacUpdate051215_GSNewDLAnythingBanner&utm_source=MacUpdate051215_GSNewDLAnythingBanner&utm_medium=email

**Comment by xiaoyifan** [comment]
Thanks Bob. It seems all users who registered will have 7 days free downloading ( 20 images a day ). I just registered.: )
