### ISSUE TITLE
Challenge - Zooming like Tiny Wings

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#80]
In Tiny Wings, the app smoothly zooms in and out while you are playing.  I was trying to achieve a similar effect and was unable to do so.  I can resize the scene, but the touches are translated on the the shrunken scene.

I called this method which does resize the SKScene:

```
 CGSize size = CGSizeMake(self.frame.size.width*1.2, self.frame.size.height*1.2);
```

If anyone can figure this out, you win the chance to walk Jonny's dog.

**Comment by yiqin** [comment]
Maybe something like this?

``` Swift
runAction(SKAction.scaleTo(1.2, duration:NSTimeInterval(0.1)))
```

**Comment by tabinks** [comment]
I tried that, but it also messes up all the touch points.

**Comment by JRam13** [comment]
Hey Andrew, I'm not sure by what you mean when you say

> but the touches are translated on the the shrunken scene.

and how it affects the game. Care to elaborate a bit more?

**Comment by JRam13** [comment]
By the way, the draw distance in that game is pretty impressive. Not a lot is happening onscreen so I guess it isn't a big performance issue. Do you know what framework they used for this game?
