### ISSUE TITLE
iCloud in Simulator

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#81]
Does anyone have this error when using iCloud?

``` Swift
There is an error:<CKError 0x7fa9aae33b10: "Internal Error" (1/1000); "Received a didCompleteWithError without receiving a response from the server">
```

``` Swift
<CKError 0x7fa9adc0ba20: "Not Authenticated" (9/1002); "This request requires an authenticated account"; Retry after 3.0 seconds>
```

The app runs very well in the iPhone device, but it has some errors when the app runs in the simulator.

**Comment by Jerry-J-Yu** [comment]
Try logging out of iCloud on your device and then logging in from the simulator.

**Comment by 0xjorgev** [comment]
That my dear Jerry did the trick! thanks for sharing
