### ISSUE TITLE
The mystery meat of mobile navigation

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#84]
I thought you guys would appreciate this. If you're interested in mobile UI, Luke Wroblewski has some great stuff.

https://twitter.com/lukew/status/591296890030915585

![cds1y0aw0aeq1l7 png-large](https://cloud.githubusercontent.com/assets/1236521/7707695/bc6d4284-fe16-11e4-87ed-9a5242636597.png)

**Comment by JRam13** [comment]
They did not go 
![image](https://cloud.githubusercontent.com/assets/3259292/7708453/627a2648-fe1b-11e4-8453-16dd39ee66d0.png)
on us!

**Comment by JRam13** [comment]
I'm sorry, but if you have a double hamburger...

![image](https://cloud.githubusercontent.com/assets/3259292/7708666/cfce10fa-fe1c-11e4-84f9-32783339e2cd.png)

**Comment by JRam13** [comment]
![image](https://cloud.githubusercontent.com/assets/3259292/7708942/29367b3a-fe1f-11e4-894d-f3070c9c7a1d.png)
