### ISSUE TITLE
Checking the internet connection is more important than I thought.

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#88]
Here is a good example. My app got more than 100 crashes in only one month. The reason is that the app doesn't connect to the Internet.

![screen shot 2015-05-21 at 10 07 16 pm](https://cloud.githubusercontent.com/assets/4560331/7763415/ded98116-0005-11e5-85cd-f64f0f19a9df.png)

**Comment by tabinks** [comment]
Does Parse have any APIs to check connections.  It seems odd that PFQuery could crash.

**Comment by JRam13** [comment]
Well, you should be checking network before making any calls to Parse. However, Parse queries shouldn't crash anyway, they send a network unavailable error block.
