### ISSUE TITLE
Office Hours Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Spring-Forum#9]
Jonny:  4:30-6:30 on Thursday as CSIL2
Bobby:   3:00-5:00 on  Fridays at CSIL1
Andrew: 12:30-1:30 on either Wednesday/Thursday in Young 306 (I will post which day during the week)

**Comment by JRam13** [comment]
::cough cough:: Jonny ::cough::

**Comment by tabinks** [comment]
The **h** is `Optional`.  Second swift joke of the day.
