### ISSUE TITLE
finding file URL returns nil

### ISSUE THREAD

**Issue by xiaoyifan** [uchicago-mobi/2015-Spring-Forum#91]
I store the data from iOS app by using plist and get the URL by using following code.
[[NSFileManager defaultManager]
                      containerURLForSecurityApplicationGroupIdentifier:
                      appGroup];

However, I can see things saved with no problem, but cannot be fetched in the watch extension. the returning value is nil.
Any idea on this?

**Comment by tabinks** [comment]
Make sure that the data is writing correctly.  Try reading the data from the app to make sure you can see it.  What you have here looks ok.

**Comment by xiaoyifan** [comment]
ahh.....it's solved, I forgot to open the App Group switch in watchkit

**Comment by xiaoyifan** [comment]
Thanks!
