### ISSUE TITLE
Error to create the WatchKit App

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Spring-Forum#92]
I got this error. Anyone can help me?
![screen shot 2015-05-24 at 9 44 51 pm](https://cloud.githubusercontent.com/assets/4560331/7791089/7efdd9d4-025f-11e5-9785-d7bdb5d94e56.png)

**Comment by tabinks** [comment]
Make sure you are including WatchKit framework in target, not just `import WatchKit`.

**Comment by yiqin** [comment]
@tabinks fixed it.
