### ISSUE TITLE
Save to server with bad network connection

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Spring-Forum#98]
Is their a best practice for saving content to a server with bad/no network connection and having it upload once it regains a connection?  I'm using Parse if that makes it an easier problem to solve.

**Comment by tabinks** [comment]
If the data is important and can't (or would be annoying to the user) to recreate than it would be wise to do something like the following:
1. Save it locally (just stash it in user defaults or write to a file)
2. Add a flag in `NSUserDefaults` like `pendingUpload=true`
3. Attempt to upload
   - If successful, delete local data and set `pendingUpload=false`
   - If not successful, do nothing
4. In background, periodically check for connectivity.  If you have network access then call a method that checks the `pendingUpload` value and attempts upload.

``` swift
if pendingUpload == true {
    // Do upload
    if successful {
       pendingUpload=false
   }
}
```

**Comment by jhergott** [comment]
Thank you!
